### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by De1fino** [HexoCraft/AddLight#19] opened 2018-01-28 11:10 UTC
There was a bug in plugin 4.2.0.
The light did not light up from the height of **125 blocks**.

I'd be happy to update it soon.

**Comment by Selebrator** [comment] 2018-02-13 17:10
Duplicate of #18

**Comment by hexosse** [comment] 2018-02-14 19:33
working on it.
thanks

**Closed by hexosse** 2018-02-14 19:33 UTC
Labels: duplicate

**Comment by hexosse** [comment] 2018-04-30 14:09
Just found a solution.
Update to AddLight 4.2.1
